version: "3.8"

services: 
  mysql:
    container_name: mysql-server
    image: mysql:5.7.40
    ports:
      - 33061:3306
  redis:
    container_name: redis-server
    image: redis:7.0.5
    ports:
      - 6379:6379
